version: "3"

# Test commands

services:
  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-networks

  backend:
    build: ./backend
    container_name: node-api
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - database
    networks:
      - mern-networks

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/mongo-db:/data/db
    networks:
      - mern-networks

networks:
  mern-networks:
    driver: bridge
